version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TEMP_STORAGE=true
      - CONTAINER_DATA_PATH=/tmp/containers
    volumes:
      # 挂载Docker socket以便管理用户容器
      - /host/var/run/docker.sock:/var/run/docker.sock
      # 数据持久化到临时存储区 (适用于Codespace临时环境)
      - /tmp/app-data:/app/data
      - /tmp/app-logs:/app/logs
      # 挂载容器临时存储目录
      - /tmp/containers:/tmp/containers
    network_mode: host
    restart: unless-stopped

  webssh:
    build:
      context: ./backend
      dockerfile: Dockerfile.webssh
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - /host/var/run/docker.sock:/var/run/docker.sock  # 挂载Docker socket
    network_mode: host
    restart: unless-stopped

  grafana:
    build:
      context: ./backend
      dockerfile: Dockerfile.grafana
    environment:
      - NODE_ENV=production
      - GRAFANA_PORT=3003
    network_mode: host
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
      - webssh
      - grafana
    network_mode: host
    restart: unless-stopped
