version: '3.8'

services:
  grafana-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana-analytics
    restart: unless-stopped
    ports:
      - "3001:3001"  # 主应用端口（包含前端静态文件）
      - "3002:3002"  # WebSSH端口
      - "5173:5173"  # 前端开发服务器端口
      - "8080:8080"  # Grafana监控界面端口
    volumes:
      # 挂载Docker socket以便管理用户容器
      - /var/run/docker.sock:/var/run/docker.sock
      # 数据持久化到临时存储区 (适用于Codespace临时环境)
      - /tmp/app-data:/app/backend/data
      - /tmp/app-logs:/app/logs
      # 挂载容器临时存储目录
      - /tmp/containers:/tmp/containers
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WEBSSH_PORT=3002
      - GRAFANA_PORT=8080
      - TEMP_STORAGE=true
      - CONTAINER_DATA_PATH=/tmp/containers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

# 注释掉持久化卷，改用临时存储
# volumes:
#   ollama-ml-data:
#     driver: local
#   ollama-ml-logs:
#     driver: local
