version: '3.8'

services:
  linuxdo-webssh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linuxdo-webssh
    restart: unless-stopped
    ports:
      - "3001:3001"  # 主应用端口（包含前端静态文件）
      - "3002:3002"  # WebSSH端口
    volumes:
      # 挂载Docker socket以便管理用户容器
      - /var/run/docker.sock:/var/run/docker.sock
      # 数据持久化
      - linuxdo-data:/app/backend/data
      - linuxdo-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WEBSSH_PORT=3002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

volumes:
  linuxdo-data:
    driver: local
  linuxdo-logs:
    driver: local
