version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TEMP_STORAGE=true
      - CONTAINER_DATA_PATH=/tmp/containers
    volumes:
      # 挂载Docker socket以便管理用户容器
      - /var/run/docker.sock:/var/run/docker.sock
      # 数据持久化到临时存储区 (适用于Codespace临时环境)
      - /tmp/app-data:/app/data
      - /tmp/app-logs:/app/logs
      # 挂载容器临时存储目录
      - /tmp/containers:/tmp/containers
    expose:
      - "3001"
    restart: unless-stopped

  webssh:
    build:
      context: ./backend
      dockerfile: Dockerfile.webssh
    environment:
      - NODE_ENV=production
      - PORT=3002
    expose:
      - "3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 挂载Docker socket
    restart: unless-stopped

  grafana:
    build:
      context: ./backend
      dockerfile: Dockerfile.grafana
    environment:
      - NODE_ENV=production
      - GRAFANA_PORT=8080
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
      - webssh
      - grafana
    ports:
      - "8080:80"        # ✅ 外网只看见这一个端口
    restart: unless-stopped
